services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
    volumes:
      - ./data/mongodata:/data/mongodata
  app:
    build: .
    image: acrho-rest
    ports:
      - 8080:8080
    links:
      - mongodb